### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [pedroCX486/noizee#5]
Whenever I try to visit it I get `Invalid Host header`

**Comment by pedroCX486** [comment]
> Whenever I try to visit it I get `Invalid Host header`

Can you give more info?

Trying to run locally or trying to access the online demo?

**Comment by EsmailELBoBDev2** [comment]
reverse proxy

**Comment by pedroCX486** [comment]
Are you running it using ‘ng serve’ or simply compiling? The project is static when compiled, so the error should be on your server, but if you’re using ng serve, I added a commit that may fix this (for development only) but if you’re running in production, this isn’t recommended.

Can you test with the latest commit?

**Comment by EsmailELBoBDev2** [comment]
well, I have problems with 3 sites so when I fix them I will test your commit and let you know

thanks

**Comment by EsmailELBoBDev2** [comment]
Hi, when  I use `npm start` I get errors like:
```
Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/debian/docker-compose/noizee/node_modules/@types/node/ts4.8/timers'
```

**Comment by EsmailELBoBDev2** [comment]
Hi again, let me tell you I suck with npm. but I found solution https://stackoverflow.com/a/55763478 and now it works :tada: noizee.esmailelbob.xyz
